### ISSUE TITLE
Is it possible to adjust the amount of time allowed for receiving payments?  

### ISSUE THREAD

**Issue by bgolat** [brainblocks/brainblocks-shopify#8]
Sometimes the exchanges may take longer than the 300seconds to process and send payments.  Is it possible to have this adjustable or is there a tech reason it is set to that timeframe?

**Comment by schenkty** [comment]
We do not support sending payments from an exchange. Further, it is not secure to store funds on an exchange.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
